import { REPO_URL, DEVPOST_URL, DEMO_URL } from '../constants'

function Hero() {
  return (
    <section className="hero" id="top">
      <div className="hero-copy">
        <p className="eyebrow">Water Quality Analysis Platform</p>
        <h1>From water sample to filter blueprint.</h1>
        <p className="hero-text">
          A research platform for water-purification scientists. A genetic algorithm proposes
          molecular lattices; first-principles quantum chemistry on{' '}
          <strong>real IBM&nbsp;Quantum hardware</strong> scores them. From a Barcelona water
          sample to a lab-ready filter blueprint in minutes.
        </p>
        <div className="cta-row">
          <a className="cta cta-primary" href={REPO_URL} target="_blank" rel="noreferrer">
            View on GitHub
          </a>
          <a className="cta cta-secondary" href={DEVPOST_URL} target="_blank" rel="noreferrer">
            Read on Devpost
          </a>
          <a className="cta cta-ghost" href={DEMO_URL} target="_blank" rel="noreferrer">
            Watch the demo
          </a>
        </div>
      </div>

      <div className="hero-panel">
        <figure className="hero-frame" data-fallback="3D molecular lattice">
          <img
            src="/screenshots/lattice.png"
            alt="3D molecular lattice generated by Blau"
            width={1280}
            height={800}
            loading="eager"
            fetchPriority="high"
          />
          <figcaption className="hero-frame-caption">
            Generated graphene lattice with -COOH edge groups
          </figcaption>
        </figure>
        <div className="mini-stats">
          <article>
            <p>Method</p>
            <strong>Genetic algorithm + quantum chemistry</strong>
          </article>
          <article>
            <p>Quantum runtime</p>
            <strong>PennyLane VQE on IBM&nbsp;Quantum</strong>
          </article>
          <article>
            <p>Hardware companion</p>
            <strong>Arduino UNO Q · Qualcomm QRB2210</strong>
          </article>
        </div>
      </div>
    </section>
  )
}

export default Hero
